In [1]:
import numpy as np # importing numpy library.

In [2]:
print("Numpy version: ", np.__version__, "\nCongigurations: ")
np.show_config()

Numpy version:  1.19.5 
Congigurations: 
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
np.zeros(10) # Vector of 10 Zeros or 10 Null values.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
_null = np.zeros((10, 10))
print("Memory Size of _null array: {} bytes".format(_null.size * _null.itemsize))
# Size of an array in bytes using .size and .itemsize attributes on _null array.

Memory Size of _null array: 800 bytes


In [5]:
np.info(np.add) # Checking the documentation by using np.info(__any attribte or method__) to get info 

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
_null = np.zeros(10) # index 4 value is one.
_null[4] = 1
_null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
_vect = np.arange(10,50) # create a vector contaning value from 10 to 49
_vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
_vect[::-1] # Reverse the Above vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
np.arange(0,9).reshape(3,3) # 3*3 Matrix using arange method and reshape it to 3*3 matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
_zero = np.array([1,2,0,0,4,0]) # getting the index of non zero values
# np.count_nonzero() method return number of non zero value in sequence
# _zero.nonzero() method return array of values that are non zero.
np.count_nonzero(_zero) # _zero.nonzero() 

3

In [11]:
np.eye(3) # 3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((3,3,3)) # 3x3x3 array with random 3 values in each row.

array([[[0.66718243, 0.53539392, 0.05616782],
        [0.07538551, 0.5887968 , 0.48329917],
        [0.43580759, 0.03498538, 0.33432005]],

       [[0.36240633, 0.14054768, 0.60232209],
        [0.26754555, 0.47794923, 0.99175084],
        [0.95801756, 0.70241234, 0.80650396]],

       [[0.33804456, 0.31925409, 0.89767027],
        [0.74178245, 0.01592966, 0.25978969],
        [0.3515326 , 0.29934561, 0.64030415]]])

In [13]:
# finding max and min value form a random number array of 10 * 10
max_min = np.random.random((10,10))
print("Array: \n", max_min)
print("Max value in array: ", max_min.max())
print("Min value in array: ", max_min.min())

Array: 
 [[0.56822608 0.27855202 0.79921518 0.89577923 0.49102436 0.8242691
  0.26899913 0.27189156 0.79633073 0.91356609]
 [0.45008623 0.8207351  0.48786405 0.54974611 0.83611139 0.71338761
  0.83218108 0.21909671 0.12380499 0.27363398]
 [0.38888436 0.21781864 0.19962318 0.25302413 0.17982771 0.20710401
  0.60206036 0.51477706 0.48361182 0.55874635]
 [0.23915226 0.34692339 0.80900659 0.53390981 0.69167407 0.12439393
  0.61613628 0.36762743 0.11215676 0.37017391]
 [0.22612625 0.3817104  0.48660509 0.24201307 0.99570912 0.93097268
  0.4176369  0.13553148 0.31486706 0.04114844]
 [0.78477511 0.4521233  0.73600954 0.41963323 0.83753701 0.83644882
  0.19830057 0.21505829 0.46928016 0.23290159]
 [0.11072978 0.22109132 0.24946483 0.70485698 0.03467487 0.08668347
  0.00661414 0.99304986 0.49607246 0.27184734]
 [0.00383883 0.8418991  0.03183237 0.52972664 0.50374026 0.27221361
  0.00663194 0.45517099 0.62972645 0.42624312]
 [0.17276917 0.84576073 0.61798583 0.88163986 0.80410592 0.2055359
  0.4

In [14]:
_vect = np.random.random(30)
print("Mean of Vector: ", _vect.mean())

Mean of Vector:  0.4105747417368539


In [15]:
# matrix containg 1 on its border and zeros inside
one_zero = np.ones((10,10))
one_zero[1:-1,1:-1] = 0 # fancy slicing is used
one_zero

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
zero_one = np.ones((5,5))
np.pad(zero_one, pad_width=1, mode="constant", constant_values=0)
# using np.pad method we can fill the border of the array with any values

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.info(np.pad)

 pad(*args, **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with

In [18]:
a = [1, 2, 3, 4, 5]
np.pad(a, (3, 3), 'constant', constant_values=(4, 6))

array([4, 4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [19]:
# result of the follwing expresion
# NaN = not a number, inf = infinity
print("0 * np.nan: ", 0 * np.nan)
print("np.nan == np.nan:", np.nan == np.nan)
print("np.inf > np.nan:", np.inf > np.nan)
print("np.nan - np.nan: ",np.nan - np.nan)
print("np.nan in set([np.nan]): ", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1: ",0.3 == 3 * 0.1)

0 * np.nan:  nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan:  nan
np.nan in set([np.nan]):  True
0.3 == 3 * 0.1:  False


In [20]:
# matrix containg values just below the diaglon 1,2,3,4
_mat = np.diag(1 + np.arange(4), k=-1)
_mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
np.info(np.diag)

 diag(*args, **kwargs)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> 

In [22]:
# 8*8 Array containg checkboard pattren
_zero = np.zeros((8,8), dtype=int)
_zero[1::2, ::2] = 1
_zero[::2, 1::2] = 1
_zero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
np.info(np.unravel_index)

 unravel_index(*args, **kwargs)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1])

In [24]:
# _zero = np.zeros((1,5,3))
np.unravel_index(99, (6,7,8))
# getting index of 100th element in an array of (6,7,8) which is (1,5,3) => 1st matrix 5th row 3rd coloum

(1, 5, 3)

In [25]:
np.info(np.tile)

 tile(*args, **kwargs)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an a

In [26]:
np.tile(np.array([[0,1], [1,0]]), (2,2))

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [27]:
# normalizing a random 5*5 matrix
_mat = np.random.random((5,5))
_mat = (_mat - np.mean(_mat))/np.std(_mat)
_mat

array([[ 1.03249309,  0.4967902 ,  0.3677121 , -1.64517081, -0.13884269],
       [ 0.61114158, -1.55263151, -0.04879052, -1.29947253, -1.63769987],
       [ 0.50350842, -1.44181329,  1.04031447, -0.15299202, -0.36575729],
       [ 0.23804326,  0.47478017,  1.23575828,  1.2509709 ,  0.85478177],
       [-1.11816261,  1.03082733, -1.43385044,  1.15051095,  0.54755106]])

In [28]:
# custom dtype that describe a color as a four unsigned bytes
np.dtype([('R', np.ubyte),
        ('B', np.ubyte),
        ('G', np.ubyte),
        ('A', np.ubyte)])

dtype([('R', 'u1'), ('B', 'u1'), ('G', 'u1'), ('A', 'u1')])

In [29]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
_mat1 = np.ones((5,3))
_mat2 = np.ones((3,2))
np.dot(_mat1, _mat2)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [30]:
# alternate solution of above cell
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [31]:
# negate all the element between 3 and 8
_vect = np.arange(11)
_vect[(3 < _vect ) & (_vect < 8)] # can use marker as a *= -1 to identify values.
_vect

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# the output will be 9 & 10. If you run cell again the output will be 10 & 10

9
10


In [58]:
_vector = np.arange(5)
# _vector**_vector
# 2 << _vector >> 2
# _vector <- _vector
# 1j*_vector
# _vector/1/1
# _vector.any() < _vector.any() >_vector.any() # it can also use all() method

array([0, 1, 2, 4, 8], dtype=int32)

In [41]:
np.info(2 << _vector >> 2)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x197b5ca25c0
byteorder:  little
byteswap:  False
type: int32


10
10
